codecov:
  token: 23d4e0d8-6a7d-47fe-a2ac-9fedcbc155b3
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...75"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  - "setup.py"

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
